let que = document.querySelector(".ques input");
let opt = document.querySelectorAll(".options button");
let next = document.querySelector(".next-button");
let quesNo = document.querySelector(".ques-no");
let startScreen = document.querySelector("#start-screen");
let startButton = document.querySelector("#start-button");
let quizScreen = document.querySelector("#quiz-screen");
let endScreen = document.querySelector("#result-screen");
let scoreBoard = document.querySelector("#score");

let game = [
    {
        question: "My computer virus was generated by:",
        options: ["Compiler", "Assembler", "Spammers", "Programmer"],
        correct: "Programmer"
    },
    {
        question: "Which HTML tag is used to create a hyperlink?",
        options: ["<link>", "<a>", "<href>", "<url>"],
        correct: "<a>"
    },
    {
        question: "RAM stands for:",
        options: ["Read After Memory", "Random Access Memory", "Rapid Access Mode", "Run All Memory"],
        correct: "Random Access Memory"
    },
    {
        question: "CSS stands for:",
        options: ["Cascading Style Sheets", "Computer Styling System", "Creative Style Syntax", "Colorful Style Sheets"],
        correct: "Cascading Style Sheets"
    },
    {
        question: "Which part of JavaScript can change HTML content?",
        options: ["DOM", "API", "Compiler", "Linker"],
        correct: "DOM"
    }
];


let ans = [];
let currentQues = 0;
let timer;
let correct = 0;
let totalQues = game.length;

startButton.addEventListener("click", startQuiz);
next.addEventListener("click", nextQues);

function startQuiz() {
    startScreen.classList.remove("active");
    quizScreen.classList.add("active");
    quesNo.textContent = 0;
    currentQues = 0;
    ans = [];
    displayQues();
}

function displayQues() {
    clearInterval(timer);
    if (currentQues < game.length) {
        quesNo.textContent = parseInt(quesNo.textContent) + 1;
        que.value = game[currentQues].question;
        next.disabled = true;
        opt.forEach((btn, index) => {
            btn.textContent = game[currentQues].options[index];
            btn.disabled = false;
            btn.classList.remove("selected");
            btn.onclick = () => {
                opt.forEach(b => b.classList.remove("selected"));
                btn.classList.add("selected");
                checkAns(game[currentQues].options[index]);
                opt.forEach(b => b.disabled = true);
                next.disabled = false;
            };
        });
        timer = setInterval(() => {
            nextQues();
        }, 10000);
    } else {
        clearInterval(timer);
        displayRes();
    }
}

function nextQues() {
    currentQues++;
    displayQues();
}

function checkAns(selected) {
    ans.push(selected === game[currentQues].correct);
}

function displayRes() {
    quizScreen.classList.remove("active");
    endScreen.classList.add("active");
    correct = ans.filter(a => a).length;
    scoreBoard.textContent = `${correct} / ${totalQues}`;
}
